package com.messq.ops;
import com.messq.auth.*;
import org.springframework.stereotype.Service;
import org.springframework.security.crypto.password.PasswordEncoder;
import java.util.*;
import java.time.*;
import static com.messq.ops.Store.*;
@Service
public class ManagementService {
 final Store s;final Access access;final DiningService dining;final AccountRepository accounts;final PasswordEncoder passwords;
 public ManagementService(Store s,Access access,DiningService dining,AccountRepository accounts,PasswordEncoder passwords){this.s=s;this.access=access;this.dining=dining;this.accounts=accounts;this.passwords=passwords;}
 public Ui.Result apply(String op,Account a,long m,Map<String,String> p){
  switch(op){
   case "menu.save"->{access.staff(a,"MENU_MANAGE");s.insert("menu_items",data("mess_id",m,"name",text(p,"name",120),"meal",choice(p,"meal","BREAKFAST","LUNCH","SNACKS","DINNER","CANTEEN"),"meal_date",date(p,"date"),"price_cents",integer(p,"price",0,10000)*100L,"vegetarian",!"NONVEG".equals(p.get("diet")),"dietary_tag",choice(p,"diet","VEGETARIAN","NONVEG","VEGAN","JAIN"),"allergens",optional(p,"allergens",500).toLowerCase(Locale.ROOT),"calories",integer(p,"calories",0,5000),"protein",integer(p,"protein",0,500)));}
   case "menu.toggle"->{access.staff(a,"MENU_MANAGE");var r=scoped("menu_items",m,p);s.db.update("UPDATE menu_items SET available=? WHERE id=?",!bool(r,"available"),num(r,"id"));}
   case "slot.create"->{access.staff(a,"QUEUE_MANAGE");LocalDate day=date(p,"date");OffsetDateTime start,end;try{start=day.atTime(LocalTime.parse(text(p,"start",5))).atZone(dining.clock.getZone()).toOffsetDateTime();end=day.atTime(LocalTime.parse(text(p,"end",5))).atZone(dining.clock.getZone()).toOffsetDateTime();}catch(Exception e){throw error(400,"Times must use HH:mm");}if(!end.isAfter(start)||!start.isAfter(dining.now()))throw error(400,"Choose a future slot with end after start");s.insert("meal_slots",data("mess_id",m,"meal",dining.meal(p),"meal_date",day,"starts_at",start,"ends_at",end,"capacity",integer(p,"capacity",1,1000)));}
   case "table.state"->{access.staff(a,"QUEUE_MANAGE");var r=scoped("tables_state",m,p);s.db.update("UPDATE tables_state SET status=? WHERE id=?",choice(p,"status","AVAILABLE","OCCUPIED","CLEANING","UNAVAILABLE"),num(r,"id"));}
   case "table.create"->{access.admin(a);s.insert("tables_state",data("mess_id",m,"label",text(p,"label",30),"seats",integer(p,"seats",1,20)));}
   case "mess.create"->{access.admin(a);s.insert("messes",data("name",text(p,"name",120),"seats",integer(p,"seats",1,5000)));}
   case "mess.status"->{access.admin(a);s.db.update("UPDATE messes SET status=? WHERE id=?",choice(p,"status","OPEN","LIMITED","CLOSED"),m);}
   case "user.create"->{access.admin(a);String email=text(p,"email",254).toLowerCase(Locale.ROOT);if(!email.matches("[^@\\s]+@[^@\\s]+\\.[^@\\s]+"))throw error(400,"Invalid email");String pass=text(p,"password",72);if(pass.length()<12||pass.getBytes(java.nio.charset.StandardCharsets.UTF_8).length>72)throw error(400,"Password must have 12+ characters and at most 72 UTF-8 bytes");Role role=Role.valueOf(choice(p,"role","STUDENT","STAFF","ADMIN"));Account created=accounts.saveAndFlush(new Account(text(p,"name",100),email,passwords.encode(pass),role));s.db.update("INSERT INTO profiles(user_id,mess_id,plan_active,permissions) VALUES (?,?,?,?)",created.getId(),m,role==Role.STUDENT,role==Role.STAFF?"QR_SCAN,QUEUE_MANAGE,ORDER_MANAGE,INVENTORY_MANAGE,MENU_MANAGE,COMPLAINT_MANAGE":"");}
   case "user.assign"->{access.admin(a);long target=id(p,"id"),targetMess=id(p,"mess_id");s.one("SELECT id FROM messes WHERE id=?",targetMess);s.one("SELECT id FROM accounts WHERE id=?",target);String permissions=optional(p,"permissions",500);for(String permission:permissions.split(",")){if(!permission.isBlank()&&!Set.of("QR_SCAN","QUEUE_MANAGE","ORDER_MANAGE","INVENTORY_MANAGE","MENU_MANAGE","COMPLAINT_MANAGE").contains(permission))throw error(400,"Unknown permission: "+permission);}if(s.count("SELECT COUNT(*) FROM profiles WHERE user_id=?",target)==0)s.db.update("INSERT INTO profiles(user_id) VALUES (?)",target);s.db.update("UPDATE profiles SET mess_id=?,plan_active=?,hostel=?,room=?,permissions=? WHERE user_id=?",targetMess,"true".equals(p.get("active")),optional(p,"hostel",100),optional(p,"room",30),permissions,target);}
   case "user.active"->{access.admin(a);long target=id(p,"id");if(target==a.getId())throw error(409,"You cannot deactivate yourself");s.one("SELECT id FROM accounts WHERE id=?",target);s.db.update("UPDATE accounts SET active=? WHERE id=?","true".equals(p.get("active")),target);}
   case "profile.save"->{if(s.count("SELECT COUNT(*) FROM profiles WHERE user_id=?",a.getId())==0)s.db.update("INSERT INTO profiles(user_id) VALUES (?)",a.getId());s.db.update("UPDATE profiles SET diet=?,allergens=? WHERE user_id=?",choice(p,"diet","VEGETARIAN","NONVEG","VEGAN","JAIN"),optional(p,"allergens",500).toLowerCase(Locale.ROOT),a.getId());}
   case "inventory.create"->{access.staff(a,"INVENTORY_MANAGE");s.insert("inventory",data("mess_id",m,"name",text(p,"name",120),"unit",text(p,"unit",20),"quantity",decimal(p,"quantity",false),"minimum",decimal(p,"minimum",false),"expires_on",p.getOrDefault("expiry","").isBlank()?null:date(p,"expiry"),"supplier",optional(p,"supplier",120)));}
   case "inventory.adjust"->{access.staff(a,"INVENTORY_MANAGE");var r=scoped("inventory",m,p);var amount=decimal(p,"quantity",true);if("CONSUME".equals(choice(p,"kind","ADD","CONSUME")))amount=amount.negate();if(s.db.update("UPDATE inventory SET quantity=quantity+? WHERE id=? AND quantity+?>=0",amount,num(r,"id"),amount)!=1)throw error(409,"Stock cannot be negative");s.insert("stock_transactions",data("item_id",num(r,"id"),"actor_id",a.getId(),"change_qty",amount,"reason",text(p,"reason",200)));}
   case "recipe.create"->{access.staff(a,"INVENTORY_MANAGE");String ingredients=text(p,"ingredients",3000);validateIngredients(ingredients);s.insert("recipes",data("mess_id",m,"name",text(p,"name",120),"base_servings",integer(p,"servings",1,10000),"ingredients",ingredients));}
   case "recipe.scale"->{access.staff(a,"INVENTORY_MANAGE");var r=scoped("recipes",m,p);int servings=integer(p,"servings",1,10000);double factor=servings/(double)num(r,"base_servings");StringBuilder result=new StringBuilder("For "+servings+" servings:\n");for(String line:str(r,"ingredients").split("\n")){String[] pieces=line.split(":");result.append(pieces[0]).append(": ").append(String.format(Locale.ROOT,"%.2f",Double.parseDouble(pieces[1].trim())*factor)).append("\n");}return new Ui.Result(result.toString());}
   case "batch.create"->{access.staff(a,"INVENTORY_MANAGE");s.insert("kitchen_batches",data("mess_id",m,"name",text(p,"name",120),"servings",integer(p,"servings",1,10000)));}
   case "batch.state"->{access.staff(a,"INVENTORY_MANAGE");var r=scoped("kitchen_batches",m,p);String next=choice(p,"status","COOKING","SERVING","COMPLETE");String expected=switch(str(r,"status")){case "PLANNED"->"COOKING";case "COOKING"->"SERVING";case "SERVING"->"COMPLETE";default->"";};if(!next.equals(expected))throw error(409,"Invalid cooking-batch transition");s.db.update("UPDATE kitchen_batches SET status=? WHERE id=?",next,num(r,"id"));}
   case "waste.record"->{access.staff(a,"INVENTORY_MANAGE");var prepared=decimal(p,"prepared",true);var waste=decimal(p,"waste",false);if(waste.compareTo(prepared)>0)throw error(400,"Waste cannot exceed preparation");s.insert("waste_records",data("mess_id",m,"actor_id",a.getId(),"meal_date",date(p,"date"),"prepared_kg",prepared,"waste_kg",waste,"note",optional(p,"note",300)));}
   case "safety.record"->{access.staff(a,"INVENTORY_MANAGE");java.math.BigDecimal temp=null;try{if(!p.getOrDefault("temperature","").isBlank())temp=new java.math.BigDecimal(p.get("temperature"));if(temp!=null&&(temp.doubleValue() < -100||temp.doubleValue()>300))throw new IllegalArgumentException();}catch(Exception e){throw error(400,"Invalid temperature");}s.insert("safety_logs",data("mess_id",m,"actor_id",a.getId(),"item",text(p,"item",120),"temperature",temp,"note",text(p,"note",500)));}
   case "feedback.create"->{access.student(a);s.insert("feedback",data("user_id",a.getId(),"mess_id",m,"meal_date",dining.today(),"rating",integer(p,"rating",1,5),"comment",text(p,"comment",1000)));String ref="feedback:"+m+":"+dining.today();s.insert("points_ledger",data("user_id",a.getId(),"points",2,"reason","Meal feedback","reference",ref));}
   case "complaint.create"->{access.student(a);s.insert("complaints",data("user_id",a.getId(),"mess_id",m,"category",choice(p,"category","FOOD","HYGIENE","STAFF","CROWD","PAYMENT","OTHER"),"description",text(p,"description",2000)));}
   case "complaint.state"->{access.staff(a,"COMPLAINT_MANAGE");var r=scoped("complaints",m,p);String status=choice(p,"status","ASSIGNED","IN_REVIEW","RESOLVED","CLOSED");s.db.update("UPDATE complaints SET status=?,resolution=? WHERE id=?",status,text(p,"resolution",2000),num(r,"id"));dining.notifyUser(num(r,"user_id"),"Complaint #"+num(r,"id")+" is now "+status);}
   case "announcement.create"->{access.admin(a);String title=text(p,"title",150);s.insert("announcements",data("mess_id",m,"title",title,"body",text(p,"body",2000)));for(var r:s.rows("SELECT user_id FROM profiles WHERE mess_id=?",m))dining.notifyUser(num(r,"user_id"),title);}
   case "favourite.toggle"->{access.student(a);var r=scoped("menu_items",m,p);if(s.db.update("DELETE FROM favourites WHERE user_id=? AND menu_id=?",a.getId(),num(r,"id"))==0)s.db.update("INSERT INTO favourites(user_id,menu_id) VALUES (?,?)",a.getId(),num(r,"id"));}
   case "poll.create"->{access.admin(a);String options=text(p,"options",1000);if(options.split("\\|").length<2||options.split("\\|").length>6)throw error(400,"Provide 2–6 options separated by |");s.insert("polls",data("mess_id",m,"question",text(p,"question",150),"options_text",options,"closes_at",date(p,"date").plusDays(1).atStartOfDay(dining.clock.getZone()).toOffsetDateTime()));}
   case "poll.vote"->{access.student(a);var r=scoped("polls",m,p);if(!time(r.get("closes_at")).isAfter(dining.now()))throw error(409,"Voting closed");int choice=integer(p,"choice",0,str(r,"options_text").split("\\|").length-1);s.db.update("INSERT INTO votes(poll_id,user_id,choice) VALUES (?,?,?)",num(r,"id"),a.getId(),choice);}
   case "event.create"->{access.admin(a);s.insert("events",data("mess_id",m,"title",text(p,"title",150),"starts_at",date(p,"date").atTime(19,0).atZone(dining.clock.getZone()).toOffsetDateTime(),"capacity",integer(p,"capacity",1,5000)));}
   case "event.book"->{access.student(a);var r=scoped("events",m,p);if(!time(r.get("starts_at")).isAfter(dining.now()))throw error(409,"Event has started");if(s.count("SELECT COUNT(*) FROM event_bookings WHERE event_id=?",num(r,"id"))>=num(r,"capacity"))throw error(409,"Event is full");s.db.update("INSERT INTO event_bookings(event_id,user_id) VALUES (?,?)",num(r,"id"),a.getId());}
   case "event.cancel"->{access.student(a);scoped("events",m,p);s.db.update("DELETE FROM event_bookings WHERE event_id=? AND user_id=?",id(p,"id"),a.getId());}
   case "guest.request"->{access.student(a);LocalDate day=date(p,"date");if(day.isBefore(dining.today()))throw error(400,"Choose today or a future date");s.insert("guest_requests",data("user_id",a.getId(),"mess_id",m,"guest_name",text(p,"name",100),"visit_date",day));}
   case "guest.state"->{access.admin(a);var r=scoped("guest_requests",m,p);s.db.update("UPDATE guest_requests SET status=? WHERE id=?",choice(p,"status","APPROVED","REJECTED"),num(r,"id"));dining.notifyUser(num(r,"user_id"),"Guest request #"+num(r,"id")+" updated.");}
   case "coupon.create"->{access.admin(a);s.insert("coupons",data("mess_id",m,"code",text(p,"code",30).toUpperCase(Locale.ROOT),"discount_percent",integer(p,"percent",1,80),"minimum_cents",integer(p,"minimum",0,10000)*100L,"expires_on",date(p,"date"),"usage_limit",integer(p,"limit",1,10000)));}
   case "notification.read"->{var r=s.one("SELECT * FROM notifications WHERE id=?",id(p,"id"));access.owner(a,r);s.db.update("UPDATE notifications SET is_read=TRUE WHERE id=?",num(r,"id"));}
   default->throw error(404,"Unknown operation");
  }
  return new Ui.Result("Saved successfully");
 }
 Map<String,Object> scoped(String table,long mess,Map<String,String> p){var r=s.one("SELECT * FROM "+table+" WHERE id=?",id(p,"id"));access.scope(mess,r);return r;}
 void validateIngredients(String text){try{for(String line:text.split("\n")){String[] pair=line.split(":");if(pair.length!=2||pair[0].isBlank()||Double.parseDouble(pair[1].trim())<=0||!Double.isFinite(Double.parseDouble(pair[1].trim())))throw new IllegalArgumentException();}}catch(Exception e){throw error(400,"Use one ingredient per line, for example Rice kg: 10");}}
}
