package com.messq.ops;
import com.messq.auth.*;
import org.springframework.stereotype.Service;
import java.util.*;
import com.messq.ops.Ui.Module;
import java.time.*;
import static com.messq.ops.Store.*;
import static com.messq.ops.Ui.*;
@Service
public class Pages {
 final Store s;final Access access;final DiningService dining;final CommerceService commerce;final InsightService insights;
 public Pages(Store s,Access access,DiningService dining,CommerceService commerce,InsightService insights){this.s=s;this.access=access;this.dining=dining;this.commerce=commerce;this.insights=insights;}
 String today(){return dining.today().toString();}
 Field dateField(){return field("date","Date (YYYY-MM-DD)","date",true,today());}
 Field mealField(){return field("meal","Meal","choice",true,"DINNER","BREAKFAST","LUNCH","SNACKS","DINNER");}
 Field number(String key,String title,String initial){return field(key,title,"number",true,initial);}
 Map<String,String> idParam(Map<String,Object> r){return Map.of("id",str(r,"id"));}
 String rupees(long cents){return "₹"+String.format(Locale.ROOT,"%.2f",cents/100.0);}
 public Workspace workspace(Account a){
  List<Module> modules=new ArrayList<>();modules.add(new Module("home","Home"));
  if(a.getRole()==Role.STUDENT){add(modules,"menu","Meals","queue","Queue","slots","Book a slot","bookings","My bookings","canteen","Canteen","orders","My orders","wallet","Wallet","map","Live mess","feedback","Feedback","complaints","Complaints","skips","Skip a meal","favourites","Favourites","polls","Menu votes","events","Events","guests","Guest meals","rewards","My impact");}
  else {add(modules,"queue","Queue desk","orders","Orders","map","Dining tables","inventory","Inventory","kitchen","Kitchen","recipes","Recipes","waste","Food waste","safety","Safety logs","complaints","Complaints","menu","Menus","slots","Meal slots","analytics","Analytics","predictions","Forecasts");if(a.getRole()==Role.ADMIN)add(modules,"users","Users","messes","Messes","announcements","Announcements","coupons","Coupons","polls","Menu votes","events","Events","guests","Guest requests","audit","Audit log");}
  add(modules,"announcements","Notices","notifications","Notifications","ai","MessQ AI","profile","Profile");
  List<Module> unique=modules.stream().collect(java.util.stream.Collectors.toMap(Module::key,x->x,(x,y)->x,LinkedHashMap::new)).values().stream().toList();
  long m=num(access.profile(a),"mess_id");String name=m==0?"Assignment pending":str(s.one("SELECT name FROM messes WHERE id=?",m),"name");
  return new Workspace(name,a.getRole().name(),unique,commerce.mockPayments);
 }
 void add(List<Module> modules,String... values){for(int i=0;i<values.length;i+=2)modules.add(new Module(values[i],values[i+1]));}
 public Page page(Account a,String module){
  if(workspace(a).modules().stream().noneMatch(x->x.key().equals(module)))throw error(403,"Module unavailable for your role");
  long m=num(access.profile(a),"mess_id");boolean student=a.getRole()==Role.STUDENT,admin=a.getRole()==Role.ADMIN;
  if(m==0&&!Set.of("profile","users","messes").contains(module))return Ui.page("Welcome, "+a.getName(),"Ask your administrator to assign a mess and activate your meal plan.",List.of());
  List<Card> cards=new ArrayList<>();List<Action> actions=new ArrayList<>();String title=module;
  switch(module){
   case "home"->{long queue=s.count("SELECT COUNT(*) FROM queue_entries WHERE mess_id=? AND meal_date=? AND status IN ('WAITING','CALLED')",m,dining.today());long seats=s.count("SELECT COALESCE(SUM(seats),0) FROM tables_state WHERE mess_id=? AND status='AVAILABLE'",m);long served=s.count("SELECT COUNT(*) FROM attendance WHERE mess_id=? AND meal_date=?",m,dining.today());var metrics=List.of(new Metric("Waiting",Long.toString(queue)),new Metric("Seats free",Long.toString(seats)),new Metric("Meals served",Long.toString(served)),new Metric("Service",str(s.one("SELECT status FROM messes WHERE id=?",m),"status")));
    for(var r:s.rows("SELECT * FROM menu_items WHERE mess_id=? AND meal_date=? AND meal<>'CANTEEN' AND available=TRUE ORDER BY meal,id LIMIT 12",m,dining.today()))cards.add(card(r.get("id"),str(r,"name"),str(r,"meal"),"Today"));
    if(student)actions.add(action("queue.join","Join queue",mealField()));
    return new Page("Hello, "+a.getName(),workspace(a).messName()+" · Live operational data",metrics,cards,actions,"thali");}
   case "menu","canteen","favourites"->{title=module.equals("canteen")?"Canteen":"Mess menu";
    String where=module.equals("canteen")?" AND meal='CANTEEN'":module.equals("favourites")?" AND id IN (SELECT menu_id FROM favourites WHERE user_id="+a.getId()+")":" AND meal<>'CANTEEN'";
    for(var r:s.rows("SELECT * FROM menu_items WHERE mess_id=? AND meal_date>=?"+where+" ORDER BY meal_date,id LIMIT 100",m,dining.today())){
     List<Action> ca=new ArrayList<>();if(student){ca.add(action("favourite.toggle","Favourite / unfavourite",idParam(r)));if(module.equals("canteen")&&bool(r,"available")&&str(r,"meal_date").equals(today()))ca.add(action("cart.add","Add to cart",Map.of("id",str(r,"id"),"name",str(r,"name"),"price",str(r,"price_cents"))));}else ca.add(action("menu.toggle","Toggle availability",idParam(r)));
     cards.add(new Card(str(r,"id"),str(r,"name"),str(r,"meal_date")+" · "+str(r,"meal")+"\nAllergens: "+(str(r,"allergens").isBlank()?"Not recorded; confirm with staff":str(r,"allergens"))+"\nEstimated nutrition: "+num(r,"calories")+" kcal · "+num(r,"protein")+"g protein",module.equals("canteen")?rupees(num(r,"price_cents")):(bool(r,"available")?"Available":"Sold out"),ca));}
    if(!student)actions.add(action("menu.save","Add menu item",field("name","Dish name"),field("meal","Meal","choice",true,"DINNER","BREAKFAST","LUNCH","SNACKS","DINNER","CANTEEN"),dateField(),number("price","Price ₹ (0 for included meals)","0"),field("diet","Diet","choice",true,"VEGETARIAN","VEGETARIAN","NONVEG","VEGAN","JAIN"),field("allergens","Allergens, comma separated","text",false,""),number("calories","Estimated calories","0"),number("protein","Estimated protein grams","0")));
   }
   case "queue"->{title=student?"My virtual queue":"Queue desk";String scope=student?" AND user_id="+a.getId():"";
    for(var r:s.rows("SELECT q.*,a.name FROM queue_entries q JOIN accounts a ON a.id=q.user_id WHERE q.mess_id=? AND q.meal_date=?"+scope+" ORDER BY q.joined_at,q.id LIMIT 150",m,dining.today())){
     List<Action> ca=new ArrayList<>();String status=str(r,"status");if(student&&List.of("WAITING","CALLED").contains(status))ca.add(action("queue.leave","Leave queue",idParam(r)));if(student&&"CALLED".equals(status))ca.add(action("pass.issue","Show entry QR",Map.of("meal",str(r,"meal"))));
     long ahead=s.count("SELECT COUNT(*) FROM queue_entries WHERE mess_id=? AND meal_date=? AND meal=? AND status IN ('WAITING','CALLED') AND (joined_at<? OR (joined_at=? AND id<?))",m,dining.today(),r.get("meal"),r.get("joined_at"),r.get("joined_at"),num(r,"id"));cards.add(new Card(str(r,"id"),"Token Q"+num(r,"id"),str(r,"name")+" · "+str(r,"meal")+" · "+ahead+" ahead",status,ca));}
    if(student)actions.add(action("queue.join","Join queue",mealField()));else{access.staff(a,"QUEUE_MANAGE");actions.add(action("queue.next","Call next student",mealField()));actions.add(action("pass.redeem","Scan / enter QR",field("token","QR token","scan",true,"")));}
   }
   case "slots"->{title="Meal slots";for(var r:s.rows("SELECT * FROM meal_slots WHERE mess_id=? AND ends_at>? ORDER BY starts_at LIMIT 100",m,dining.now())){long booked=s.count("SELECT COUNT(*) FROM bookings WHERE slot_id=? AND status IN ('BOOKED','CLAIMED')",num(r,"id"));cards.add(card(r.get("id"),str(r,"meal"),str(r,"starts_at")+" to "+str(r,"ends_at"),(num(r,"capacity")-booked)+" spaces",student?action("booking.create",booked>=num(r,"capacity")?"Join waitlist":"Book slot",Map.of("id",str(r,"id"),"waitlist",Boolean.toString(booked>=num(r,"capacity")))):action("slot.create","Add another slot",dateField(),mealField(),field("start","Start HH:mm"),field("end","End HH:mm"),number("capacity","Capacity","20"))));}
    if(!student){access.staff(a,"QUEUE_MANAGE");actions.add(action("slot.create","Create meal slot",dateField(),mealField(),field("start","Start HH:mm"),field("end","End HH:mm"),number("capacity","Capacity","20")));}
   }
   case "bookings"->{title="My bookings";for(var r:s.rows("SELECT b.*,s.mess_id,s.starts_at,s.ends_at,s.meal FROM bookings b JOIN meal_slots s ON s.id=b.slot_id WHERE b.user_id=? AND s.mess_id=? ORDER BY b.id DESC LIMIT 100",a.getId(),m)){List<Action> ca=new ArrayList<>();if(List.of("BOOKED","WAITLIST").contains(str(r,"status")))ca.add(action("booking.cancel","Cancel booking",idParam(r)));if("BOOKED".equals(str(r,"status")))ca.add(action("pass.issue","Show entry QR",idParam(r)));cards.add(new Card(str(r,"id"),str(r,"meal"),str(r,"starts_at"),str(r,"status"),ca));}}
   case "map"->{title="Live dining hall";for(var r:s.rows("SELECT * FROM tables_state WHERE mess_id=? ORDER BY id",m)){cards.add(student?card(r.get("id"),str(r,"label"),num(r,"seats")+" shared seats",str(r,"status")):card(r.get("id"),str(r,"label"),num(r,"seats")+" shared seats",str(r,"status"),action("table.state","Update table",idParam(r),field("status","State","choice",true,str(r,"status"),"AVAILABLE","OCCUPIED","CLEANING","UNAVAILABLE"))));}if(admin)actions.add(action("table.create","Add table",field("label","Table label"),number("seats","Seats","4")));}
   case "orders"->{title=student?"My orders":"Kitchen orders";if(!student)access.staff(a,"ORDER_MANAGE");String scope=student?" AND user_id="+a.getId():"";for(var r:s.rows("SELECT * FROM orders WHERE mess_id=?"+scope+" ORDER BY id DESC LIMIT 100",m)){var lines=s.rows("SELECT name,quantity FROM order_items WHERE order_id=?",num(r,"id"));String detail=String.join("\n",lines.stream().map(l->str(l,"name")+" × "+num(l,"quantity")).toList());List<Action> ca=new ArrayList<>();String status=str(r,"status");if(student&&status.equals("PLACED"))ca.add(action("order.state","Cancel and refund",Map.of("id",str(r,"id"),"status","CANCELLED")));if(!student){String next=switch(status){case "PLACED"->"ACCEPTED";case "ACCEPTED"->"PREPARING";case "PREPARING"->"READY";case "READY"->"COLLECTED";default->"";};if(!next.isEmpty())ca.add(action("order.state","Mark "+next,Map.of("id",str(r,"id"),"status",next)));if(List.of("PLACED","ACCEPTED").contains(status))ca.add(action("order.state","Cancel / refund",Map.of("id",str(r,"id"),"status","CANCELLED")));}cards.add(new Card(str(r,"id"),"MQ"+num(r,"id")+" · "+rupees(num(r,"total_cents")),detail,status,ca));}}
   case "wallet"->{title="My wallet";long balance=s.count("SELECT COALESCE(SUM(balance_cents),0) FROM wallets WHERE user_id=?",a.getId());cards.add(card("balance","Balance",rupees(balance),commerce.mockPayments?"Development credits":"Wallet"));for(var r:s.rows("SELECT * FROM wallet_transactions WHERE user_id=? ORDER BY id DESC LIMIT 100",a.getId()))cards.add(card(r.get("id"),str(r,"kind"),str(r,"created_at")+" · "+str(r,"reference"),rupees(num(r,"amount_cents"))));if(commerce.mockPayments)actions.add(action("wallet.topup","Add mock credit (no real charge)",number("rupees","Amount ₹","100")));}
   case "inventory"->{access.staff(a,"INVENTORY_MANAGE");title="Inventory & suppliers";for(var r:s.rows("SELECT * FROM inventory WHERE mess_id=? ORDER BY id",m)){boolean low=((Number)r.get("quantity")).doubleValue()<((Number)r.get("minimum")).doubleValue();String tag=low?"Low stock":"In stock";if(r.get("expires_on")!=null&&LocalDate.parse(str(r,"expires_on")).isBefore(dining.today().plusDays(3)))tag="Expiry soon";cards.add(card(r.get("id"),str(r,"name"),r.get("quantity")+" "+str(r,"unit")+" · Min "+r.get("minimum")+"\nSupplier: "+str(r,"supplier")+" · Expiry: "+str(r,"expires_on"),tag,action("inventory.adjust","Adjust stock",idParam(r),field("kind","Change","choice",true,"ADD","ADD","CONSUME"),number("quantity","Quantity","1"),field("reason","Reason"))));}actions.add(action("inventory.create","Add inventory item",field("name","Item"),field("unit","Unit (kg / litre / pcs)"),number("quantity","Current quantity","0"),number("minimum","Minimum stock","5"),field("expiry","Expiry YYYY-MM-DD","date",false,""),field("supplier","Supplier","text",false,"")));}
   case "kitchen"->{access.staff(a,"INVENTORY_MANAGE");title="Cooking batches";for(var r:s.rows("SELECT * FROM kitchen_batches WHERE mess_id=? ORDER BY id DESC LIMIT 100",m)){String next=switch(str(r,"status")){case "PLANNED"->"COOKING";case "COOKING"->"SERVING";case "SERVING"->"COMPLETE";default->"";};cards.add(card(r.get("id"),str(r,"name"),num(r,"servings")+" servings",str(r,"status"),next.isEmpty()?new Action[0]:new Action[]{action("batch.state","Mark "+next,Map.of("id",str(r,"id"),"status",next))}));}actions.add(action("batch.create","Plan batch",field("name","Dish / batch name"),number("servings","Servings","100")));}
   case "recipes"->{access.staff(a,"INVENTORY_MANAGE");title="Recipes";for(var r:s.rows("SELECT * FROM recipes WHERE mess_id=?",m))cards.add(card(r.get("id"),str(r,"name"),str(r,"ingredients"),num(r,"base_servings")+" servings",action("recipe.scale","Scale recipe",idParam(r),number("servings","Target servings","200"))));actions.add(action("recipe.create","Add recipe",field("name","Recipe name"),number("servings","Base servings","100"),field("ingredients","One ingredient per line: Rice kg: 10","multiline",true,"")));}
   case "waste"->{access.staff(a,"INVENTORY_MANAGE");title="Food waste";for(var r:s.rows("SELECT * FROM waste_records WHERE mess_id=? ORDER BY id DESC LIMIT 100",m))cards.add(card(r.get("id"),str(r,"meal_date"),"Prepared "+r.get("prepared_kg")+" kg · Wasted "+r.get("waste_kg")+" kg\n"+str(r,"note"),String.format(Locale.ROOT,"%.1f%%",((Number)r.get("waste_kg")).doubleValue()/((Number)r.get("prepared_kg")).doubleValue()*100)));actions.add(action("waste.record","Record waste",dateField(),number("prepared","Prepared kg","100"),number("waste","Waste kg","0"),field("note","Note","text",false,"")));}
   case "safety"->{access.staff(a,"INVENTORY_MANAGE");title="Food safety logs";for(var r:s.rows("SELECT * FROM safety_logs WHERE mess_id=? ORDER BY id DESC LIMIT 100",m))cards.add(card(r.get("id"),str(r,"item"),str(r,"note")+"\n"+str(r,"created_at"),str(r,"temperature")+" °C"));actions.add(action("safety.record","Log a check",field("item","Food / equipment / cleaning area"),field("temperature","Measured temperature °C","number",false,""),field("note","Observation and action","multiline",true,"")));}
   case "feedback"->{title="Meal feedback";for(var r:s.rows("SELECT * FROM feedback WHERE user_id=? AND mess_id=? ORDER BY id DESC LIMIT 100",a.getId(),m))cards.add(card(r.get("id"),str(r,"meal_date"),str(r,"comment"),num(r,"rating")+" / 5"));actions.add(action("feedback.create","Rate today’s meal",number("rating","Rating 1–5","4"),field("comment","Feedback","multiline",true,"")));}
   case "complaints"->{title="Complaints";if(!student)access.staff(a,"COMPLAINT_MANAGE");String scope=student?" AND user_id="+a.getId():"";for(var r:s.rows("SELECT * FROM complaints WHERE mess_id=?"+scope+" ORDER BY id DESC LIMIT 100",m))cards.add(card(r.get("id"),"#"+num(r,"id")+" · "+str(r,"category"),str(r,"description")+"\nResponse: "+str(r,"resolution"),str(r,"status"),student?new Action[0]:new Action[]{action("complaint.state","Update ticket",idParam(r),field("status","Status","choice",true,"IN_REVIEW","ASSIGNED","IN_REVIEW","RESOLVED","CLOSED"),field("resolution","Response","multiline",true,""))}));if(student)actions.add(action("complaint.create","Raise complaint",field("category","Category","choice",true,"FOOD","FOOD","HYGIENE","STAFF","CROWD","PAYMENT","OTHER"),field("description","Describe the issue","multiline",true,"")));}
   case "skips"->{title="Plan skipped meals";for(var r:s.rows("SELECT * FROM skip_meals WHERE user_id=? AND mess_id=? ORDER BY meal_date DESC LIMIT 100",a.getId(),m))cards.add(card(r.get("id"),str(r,"meal"),str(r,"meal_date"),"Skipping",action("skip.undo","Undo skip",idParam(r))));actions.add(action("skip.create","Skip a meal",dateField(),mealField()));}
   case "announcements"->{title="Campus notices";for(var r:s.rows("SELECT * FROM announcements WHERE mess_id=? ORDER BY id DESC LIMIT 100",m))cards.add(card(r.get("id"),str(r,"title"),str(r,"body"),str(r,"created_at")));if(admin)actions.add(action("announcement.create","Create announcement",field("title","Title"),field("body","Message","multiline",true,"")));}
   case "notifications"->{title="Notifications";for(var r:s.rows("SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 100",a.getId()))cards.add(card(r.get("id"),str(r,"message"),str(r,"created_at"),bool(r,"is_read")?"Read":"New",bool(r,"is_read")?new Action[0]:new Action[]{action("notification.read","Mark read",idParam(r))}));}
   case "polls"->{title="Choose your special meal";for(var r:s.rows("SELECT * FROM polls WHERE mess_id=? ORDER BY id DESC LIMIT 50",m)){String[] opts=str(r,"options_text").split("\\|");List<Action> ca=new ArrayList<>();StringBuilder desc=new StringBuilder();for(int i=0;i<opts.length;i++){long votes=s.count("SELECT COUNT(*) FROM votes WHERE poll_id=? AND choice=?",num(r,"id"),i);desc.append(opts[i]).append(": ").append(votes).append(" votes\n");if(student)ca.add(action("poll.vote",opts[i],Map.of("id",str(r,"id"),"choice",Integer.toString(i))));}cards.add(new Card(str(r,"id"),str(r,"question"),desc.toString(),"Closes "+str(r,"closes_at"),ca));}if(admin)actions.add(action("poll.create","Create menu poll",field("question","Question"),field("options","Options separated by |"),dateField()));}
   case "events"->{title="Campus meal events";for(var r:s.rows("SELECT * FROM events WHERE mess_id=? ORDER BY starts_at DESC LIMIT 50",m)){long booked=s.count("SELECT COUNT(*) FROM event_bookings WHERE event_id=?",num(r,"id"));boolean mine=s.count("SELECT COUNT(*) FROM event_bookings WHERE event_id=? AND user_id=?",num(r,"id"),a.getId())>0;cards.add(card(r.get("id"),str(r,"title"),str(r,"starts_at"),(num(r,"capacity")-booked)+" spaces",student?new Action[]{action(mine?"event.cancel":"event.book",mine?"Cancel RSVP":"RSVP",idParam(r))}:new Action[0]));}if(admin)actions.add(action("event.create","Create event",field("title","Event name"),dateField(),number("capacity","Capacity","100")));}
   case "guests"->{title=student?"Guest meal requests":"Guest approvals";String scope=student?" AND user_id="+a.getId():"";for(var r:s.rows("SELECT * FROM guest_requests WHERE mess_id=?"+scope+" ORDER BY id DESC LIMIT 100",m))cards.add(card(r.get("id"),str(r,"guest_name"),str(r,"visit_date"),str(r,"status"),admin?new Action[]{action("guest.state","Review",idParam(r),field("status","Decision","choice",true,"APPROVED","APPROVED","REJECTED"))}:new Action[0]));if(student)actions.add(action("guest.request","Request guest meal",field("name","Guest name"),dateField()));}
   case "rewards"->{title="My impact";long points=s.count("SELECT COALESCE(SUM(points),0) FROM points_ledger WHERE user_id=?",a.getId());cards.add(card("points",points+" MessQ points","Plan ahead and give useful feedback.",points>=50?"Early Planner":"Getting started"));for(var r:s.rows("SELECT * FROM points_ledger WHERE user_id=? ORDER BY id DESC LIMIT 100",a.getId()))cards.add(card(r.get("id"),str(r,"reason"),str(r,"reference"),"+"+num(r,"points")));}
   case "users" -> {
    access.admin(a); title="Campus users";
    for(var r:s.rows("SELECT a.id,a.name,a.email,a.role,a.active,p.mess_id,p.plan_active,p.hostel,p.room,p.permissions FROM accounts a LEFT JOIN profiles p ON p.user_id=a.id ORDER BY a.id LIMIT 200")) {
     Action assign=action("user.assign","Assign mess / permissions",idParam(r),
       field("mess_id","Mess ID","number",true,str(r,"mess_id")),
       field("active","Meal plan active","choice",true,Boolean.toString(bool(r,"plan_active")),"true","false"),
       field("hostel","Hostel","text",false,str(r,"hostel")),field("room","Room","text",false,str(r,"room")),
       field("permissions","Staff permission codes (comma separated)","text",false,str(r,"permissions")));
     Action active=action("user.active",bool(r,"active")?"Deactivate":"Activate",Map.of("id",str(r,"id"),"active",Boolean.toString(!bool(r,"active"))));
     cards.add(card(r.get("id"),str(r,"name"),str(r,"email")+" · Mess "+str(r,"mess_id"),str(r,"role")+(bool(r,"active")?"":" · Inactive"),assign,active));
    }
    actions.add(action("user.create","Create campus account",field("name","Name"),field("email","Email"),field("password","Temporary password (12+ characters)","password",true,""),field("role","Role","choice",true,"STAFF","STUDENT","STAFF","ADMIN")));
   }
   case "messes"->{access.admin(a);title="Campus messes";for(var r:s.rows("SELECT * FROM messes ORDER BY id"))cards.add(card(r.get("id"),str(r,"name"),"ID "+num(r,"id")+" · "+num(r,"seats")+" seats",str(r,"status")));actions.add(action("mess.create","Add mess",field("name","Mess name"),number("seats","Seat capacity","120")));if(m!=0)actions.add(action("mess.status","Change current mess service",field("status","Service status","choice",true,"OPEN","OPEN","LIMITED","CLOSED")));}
   case "coupons"->{access.admin(a);title="Canteen coupons";for(var r:s.rows("SELECT * FROM coupons WHERE mess_id=? ORDER BY id DESC",m))cards.add(card(r.get("id"),str(r,"code"),"Expires "+str(r,"expires_on")+" · Minimum "+rupees(num(r,"minimum_cents")),num(r,"discount_percent")+"% off"));actions.add(action("coupon.create","Create coupon",field("code","Code"),number("percent","Discount % (1–80)","10"),number("minimum","Minimum order ₹","100"),dateField(),number("limit","Total uses","100")));}
   case "audit"->{access.admin(a);title="Audit trail";for(var r:s.rows("SELECT * FROM audit_logs WHERE mess_id=? ORDER BY id DESC LIMIT 200",m))cards.add(card(r.get("id"),str(r,"action"),"Actor "+num(r,"actor_id")+" · "+str(r,"detail"),str(r,"created_at")));}
   case "analytics"->{if(student)throw error(403,"Staff access required");title="Mess analytics";long attendance=s.count("SELECT COUNT(*) FROM attendance WHERE mess_id=?",m),orders=s.count("SELECT COUNT(*) FROM orders WHERE mess_id=? AND status<>'CANCELLED'",m),revenue=s.count("SELECT COALESCE(SUM(total_cents),0) FROM orders WHERE mess_id=? AND status<>'CANCELLED'",m);cards.add(card("revenue","Canteen sales",rupees(revenue),commerce.mockPayments?"Mock credit transactions":"Wallet transactions"));cards.add(card("attendance","Meals claimed",Long.toString(attendance),"All recorded time"));cards.add(card("orders","Non-cancelled orders",Long.toString(orders),"All recorded time"));for(var r:s.rows("SELECT meal_date,SUM(prepared_kg) AS prepared,SUM(waste_kg) AS waste FROM waste_records WHERE mess_id=? GROUP BY meal_date ORDER BY meal_date DESC LIMIT 30",m))cards.add(card(str(r,"meal_date"),str(r,"meal_date"),"Prepared "+r.get("prepared")+"kg, waste "+r.get("waste")+"kg","Waste"));}
   case "predictions"->{if(student)throw error(403,"Staff access required");title="Demand & crowd forecasts";for(String meal:List.of("BREAKFAST","LUNCH","DINNER")){var d=insights.demand(m,meal,dining.today().plusDays(1));cards.add(card(meal,meal+" · tomorrow",str(d,"method")+"\nBooked "+d.get("booked")+" · Skips "+d.get("skips"),d.get("expected")+" expected"));}for(var r:insights.crowd(m))cards.add(card(str(r,"label"),str(r,"label"),str(r,"note"),str(r,"value")));for(var r:s.rows("SELECT * FROM forecast_history WHERE mess_id=? ORDER BY meal_date DESC LIMIT 15",m))cards.add(card(r.get("id"),str(r,"meal_date")+" · "+str(r,"meal"),"Predicted "+num(r,"predicted")+" · Actual "+str(r,"actual"),"Evaluation"));}
   case "ai"->{title="MessQ AI";for(var r:s.rows("SELECT * FROM ai_messages WHERE user_id=? ORDER BY id DESC LIMIT 15",a.getId()))cards.add(card(r.get("id"),str(r,"question"),str(r,"answer"),"AI generated"));actions.add(action("ai.ask","Ask MessQ",field("question",student?"Ask about today’s menu or your orders":"Ask for review, complaint or demand insights","multiline",true,"")));}
   case "profile"->{title="My profile";var p=access.profile(a);cards.add(card("me",a.getName(),a.getEmail(),a.getRole().name()));cards.add(card("plan",workspace(a).messName(),str(p,"hostel")+" · Room "+str(p,"room"),bool(p,"plan_active")?"Meal plan active":"No active meal plan"));actions.add(action("profile.save","Diet & allergens",field("diet","Diet","choice",true,str(p,"diet"),"VEGETARIAN","NONVEG","VEGAN","JAIN"),field("allergens","Allergens separated by commas (milk,wheat,soy…)","text",false,str(p,"allergens"))));}
   default->throw error(404,"Unknown page");
  }
  return new Page(title,"Database records · "+workspace(a).messName(),List.of(),cards,actions,module.equals("map")?"mess":"");
 }
}
